---
- hosts: all
  vars_files:
    - vars/main.yml
  become: true
  become_method: sudo
  roles:
    - geerlingguy.docker
    - davidharrigan.postgresql
    - graphite
    - collectd
    - grafana
    - nginx
