---
- name: install nginx
  apt: name=nginx update_cache=yes cache_valid_time=3600

- name: copy grafana site
  template:
    src: grafana 
    dest: /etc/nginx/sites-enabled/
  notify: restart nginx

- name: copy graphite site
  template:
    src: graphite
    dest: /etc/nginx/sites-enabled/
  notify: restart nginx

- name: remove default site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

