---
- name: install collectd
  apt: name={{ item }} update_cache=yes cache_valid_time=3600
  with_items:
    - collectd
    - collectd-utils

- name: copy collectd config
  template:
    src: "templates/collectd.conf.j2"
    dest: "/etc/collectd/collectd.conf"
  notify: restart collectd
