---
- name: create src folder
  file: path=~/src state=directory

- name: create /var/www folders
  file: path=/var/www state=directory

- name: check if sources have been downloaded
  stat: path=~/src/{{ GRAFANA_SOURCE_FILENAME }}.tar.gz
  register: grafana_download

- name: download sources
  shell: wget http://grafanarel.s3.amazonaws.com/{{ GRAFANA_SOURCE_FILENAME }}.tar.gz
  when: not grafana_download.stat.exists
  args:
    chdir: ~/src

- name: extract archive
  shell: tar -xvf {{ GRAFANA_SOURCE_FILENAME }}.tar.gz
  when: not grafana_download.stat.exists
  args:
    chdir: ~/src

- name: copy source
  shell: cp -rf ~/src/{{ GRAFANA_SOURCE_FILENAME }} /var/www/grafana

- name: grafana - chown
  shell: chown -R www-data:www-data /var/www/grafana

- name: grafana - copy config
  template: src=config.js dest=/var/www/grafana/
