---
- name: add grafana apt key
  apt_key:
    url: https://packagecloud.io/gpg.key
    state: present

- name: add grafana apt repository
  apt_repository:
    repo: deb https://packagecloud.io/grafana/stable/debian/ stretch main
    state: present
    update_cache: yes

- name: install grafana
  apt: name={{ item }} update_cache=yes cache_valid_time=3600
  with_items:
    - grafana

- name: copy grafana.ini
  template:
    src: "templates/grafana.ini.j2"
    dest: "/etc/grafana/grafana.ini"
  notify: restart grafana-server

- name: enable grafana-server service
  systemd:
    name: grafana-server
    state: started
