---
- name: add apt-key
  apt_key:
    url: https://repos.influxdata.com/influxdb.key
    state: present
  register: add_repository_key
  ignore_errors: "{{ influxdb_apt_ignore_key_error }}"

- name: add repository
  apt_repository:
    repo: "{{ influxdb_apt_repository }}"
    state: present
    update_cache: yes

- name: install influxdb
  package:
    name: "influxdb"
    state: "{{ influxdb_package_state }}"

# TODO skip these if package state is not present
- name: start service
  service: name=influxdb state=started

- name: wait for service
  wait_for: port=8086 delay=5

- name: deploy shards_default.json
  template: src=shards_default.json dest=/tmp/

- name: create project database
  shell: curl -X POST "http://localhost:8086/cluster/database_configs/{{ INFLUXDB_DATABASE }}?u=root&p=root" --data-binary @/tmp/shards_default.json

- name: create grafana database
  shell: "curl -X POST 'http://localhost:8086/cluster/database_configs/grafana?u=root&p=root' -d '{\"name\": \"grafana\"}'"

- name: create project user
  shell: "curl -X POST 'http://localhost:8086/db/{{ INFLUXDB_DATABASE }}/users?u=root&p=root' -d '{\"name\": \"{{ INFLUXDB_USER }}\", \"password\": \"{{ INFLUXDB_PASSWORD }}\"}'"

- name: create grafana user
  shell: "curl -X POST 'http://localhost:8086/db/grafana/users?u=root&p=root' -d '{\"name\": \"grafana\", \"password\": \"{{ INFLUXDB_GRAFANA_PASSWORD }}\"}'"

- name: change root pw
  shell: "curl -X POST 'http://localhost:8086/cluster_admins/root?u=root&p=root' -d '{\"password\": \"{{ INFLUXDB_ROOT_PASSWORD }}\"}'"

